import fake_spectra.voigtfit as voigtfit
from fake_spectra.plot_spectra import PlottingSpectra
import numpy as np
import pickle
import fake_spectra.fluxstatistics as fstat

# Defining some functions to save small objects using pickle for easier plotting. 
def save_obj(obj, name):
    with open(name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name):
    with open(name + '.pkl', 'rb') as f:
        return pickle.load(f)

# This function loads spectra as intended.
# I just redefined it to be more intuitive in my code to make repeat uses easier.
def load_rs(num, base, savefile, label = 'Random Spectra', quiet = False):
    
    '''
    This loads in fake spectra data generated by Fake Spectra Flux Extractor.
        Arguments:
            num - snapshot number (if the snapnum is 020 enter 20 and it will pad it with the 0)
            base - path to the location of the spectra folder
            file - name of the fake spectra save file
            label - a marker that I don't use in any of the following functions so I put a filler
            quiet - whether or not you want description print statements when loading in spectra
                    denotes the path, file name, and redshift of the spectra
                    helpful for single loads and checks, can be too much for dozens of loads
        
        e.g. if the fake spectra data is in path/to/file/SPECTRA_127/fake_spectra.hdf5
            then num = 127, base = "path/to/file/", savefile = "fake_spectra.hdf5"

    '''
    ps = PlottingSpectra(num=num, base=base, savefile=savefile, label=label, quiet=quiet)
    return ps

# Below are functions I use for comparing various statistics. 
# These are typically pulled from the master code but placed independently here usually for computation speed reasons.
def get_CDD(spectra, dLogN = 0.2,  minN = 11., maxN = 23., close = 50., dX = False, dlogn = True, line = False):
    
    '''
    This computes the absorber column density distribution function, which is the number
        of absorbers per sight line with column densities in the interval
        [N, N+dN] at the absorption distance X.
        The path can be either a whole sightline across the box, if line=True, or, if line=False,
        it can be a fixed spacing in the hubble flow.

        So we have f(N) = d n_abs/ dlogN dz by default
            with dlogN -> dN if dlogn = False
            with dz -> dX if dX = True

        Arguments:
            dlogN - bin spacing
            minN - minimum log N
            maxN - maximum log N
            close - amalgamate absorbers closer than X km/s
            dX - If true return dn/dlogN dX, if false return dn/dlogN dz
            dlogn - If true return dn/dlogN dz, if false return dn/dN dz
            line - cddf for whole line or for each cell.
        Returns:
            dlogN, f_N_table - N_HI (binned in log) and corresponding f(N)
    '''

    tot_lines = spectra.NumLos+spectra.discarded

    NHI_table = 10**np.arange(minN, maxN, dLogN)
    center = np.array([(NHI_table[i]+NHI_table[i+1])/2. for i in range(0, np.size(NHI_table)-1)])
    width = np.array([NHI_table[i+1]-NHI_table[i] for i in range(0, np.size(NHI_table)-1)])

    if line:
        cds = np.sum(spectra.get_col_density(elem="H", ion=1), axis=1)
    else:
        cds = spectra.get_col_density(elem="H", ion=1)
        cbins = np.max((int(np.round((close/spectra.dvbin))), 1))
        cdsb = np.array([np.sum(cds[:, cbins*i:cbins*(i+1)], axis=1) for i in range(int(np.shape(cds)[1]/cbins))]).T
        cds = cdsb
    
    if dlogn:
        div_width=dLogN
    else:
        div_width=width
        
    (tot_f_N, NHI_table) = np.histogram(cds, NHI_table) 
    
    if dX:
        dX=spectra.units.absorption_distance(spectra.box,spectra.red)
        tot_f_N = tot_f_N/(div_width*dX*tot_lines)
    else:
        dz = spectra.units.redshift_distance(spectra.box, spectra.red, spectra.OmegaM)
        tot_f_N = tot_f_N/(div_width*dz*tot_lines)
        
    return np.log10(center), tot_f_N


def get_voigt_CDD(spectra, elem="H", ion=1, line=1215, dLogN = 0.2, minN = 11., maxN = 23., close=0, dX=False, dlogn = True, nspectra=-1, snr=0, EMD=True):
    '''
    This computes the column density function using column densities from a Voigt profile fit.
    Concatenate objects closer than close km/s.

        Arguments:
            spectra - the loaded in spectra file generated by fake spectra
            elem - element to generate for
            ion - element ionization
            line - spectral line of interest
            dLogN - bin spacing
            minN - minimum log N
            maxN - maximum log N
            close - amalgamate absorbers closer than X km/s
            dX - If true return dn/dlogN dX, if false return dn/dlogN dz
            dlogn - If true return dn/dlogN dz, if false return dn/dN dz
            line - cddf for whole line or for each cell.
            snr - default is 0 or perfect SNR
        Returns:
            dlogN, f_N_table - N_HI (binned in log) and corresponding f(N)
            b and logN_HI - b-values and log column desntities from fits
            fit results - the resulting fits from the Voigt fitting
            tau - the optical depths that were fit
    '''

    NHI_table = 10**np.arange(minN, maxN, dLogN)
    center = np.array([(NHI_table[i]+NHI_table[i+1])/2. for i in range(0, np.size(NHI_table)-1)])
    width = np.array([NHI_table[i+1]-NHI_table[i] for i in range(0, np.size(NHI_table)-1)])
   
    tau = spectra.get_tau(elem, ion, line)

    if snr != 0:
        flux = np.exp(-tau)
        lines = np.shape(flux)[0]
        snr = np.zeros(np.shape(flux)[0]) + snr
        (flux_noise, noise) = spectra.add_noise(snr, flux)
        flux_noise[flux_noise > 1] = 1
        flux_noise[flux_noise < 0] = 0
        tau_noise = -np.log(flux_noise)
        tau = np.asarray(tau_noise)
        
    tau_filt = [tau_ind for tau_ind in tau if not (max(tau_ind) > 100)]
    tau = np.asarray(tau_filt)
        
    tot_lines = len(tau[:,0])

    n_vals, b_params, fit_results = voigtfit.get_voigt_fits_and_params(tau, spectra.dvbin, elem=elem, ion=ion, line=line, verbose=False, close=close, EMD=EMD)
    
    if dlogn:
        div_width=dLogN
    else:
        div_width=width
    
    (tot_f_N, NHI_table) = np.histogram(n_vals, NHI_table)
    
    #Absorption distance for each line
    if dX:
        dX=spectra.units.absorption_distance(spectra.box,spectra.red)
        tot_f_N = tot_f_N/(div_width*dX*tot_lines)
    else:
        dz = spectra.units.redshift_distance(spectra.box, spectra.red, spectra.OmegaM)
        tot_f_N = tot_f_N/(div_width*dz*tot_lines)
        
    return np.log10(center), tot_f_N, b_params, np.log10(n_vals), fit_results, tau


def get_voigt_CDD_UVBcorr(spectra, UVBcorr=1, elem="H", ion=1, line=1215, dLogN = 0.2, minN = 11., maxN = 23., close=0, dX=False, dlogn = True, nspectra=-1, EMD=True):
    """This computes the column density function using column densities from a Voigt profile fit.
        Concatenate objects closer than close km/s. 
        Same function as get_voigt_CDD but now correcting the flux post-processing 
        to change to assumed photoionizing rate for HI.
        
        New argument:
            UVBcorr - the factor by which you want to scale the assumed HI photoionizing rate
        """

    NHI_table = 10**np.arange(minN, maxN, dLogN)
    center = np.array([(NHI_table[i]+NHI_table[i+1])/2. for i in range(0, np.size(NHI_table)-1)])
    width = np.array([NHI_table[i+1]-NHI_table[i] for i in range(0, np.size(NHI_table)-1)])
        
    tau = spectra.get_tau(elem, ion, line)/UVBcorr

    tau_filt = [tau_ind for tau_ind in tau if not (max(tau_ind) > 100)]
    tau = np.asarray(tau_filt)
        
    tot_lines = len(tau[:,0])

    n_vals, b_params, fit_results = voigtfit.get_voigt_fits_and_params(tau, spectra.dvbin, elem=elem, ion=ion, line=line, verbose=False, close=close, EMD=EMD)
    
    if dlogn:
        div_width=dLogN
    else:
        div_width=width
    
    (tot_f_N, NHI_table) = np.histogram(n_vals, NHI_table)
    
    #Absorption distance for each line
    if dX:
        dX=spectra.units.absorption_distance(spectra.box,spectra.red)
        tot_f_N = tot_f_N/(div_width*dX*tot_lines)
    else:
        dz = spectra.units.redshift_distance(spectra.box, spectra.red, spectra.OmegaM)
        tot_f_N = tot_f_N/(div_width*dz*tot_lines)
        
    return np.log10(center), tot_f_N, b_params, np.log10(n_vals), fit_results, tau


def get_voigt_CDD_taueff(spectra, rsmatch, elem="H", ion=1, line=1215, dLogN = 0.2, minN = 11., maxN = 23., close=0, dX=False, dlogn = True, nspectra=-1, EMD=True):
    """This computes the column density function using column densities from a Voigt profile fit.
        Same function as get_voigt_CDD but now correcting the flux post-processing 
        to match the same mean flux as a secondary given spectral file.
        
        New argument:
            rematch - the spectral file you want to match the same mean flux of
        """

    NHI_table = 10**np.arange(minN, maxN, dLogN)
    center = np.array([(NHI_table[i]+NHI_table[i+1])/2. for i in range(0, np.size(NHI_table)-1)])
    width = np.array([NHI_table[i+1]-NHI_table[i] for i in range(0, np.size(NHI_table)-1)])
        
    mean_flux_desired = rsmatch.get_mean_flux(tau_thresh=1e6)
    tau = spectra.get_tau(elem, ion, line)
    scale = fstat.mean_flux(tau, mean_flux_desired)
    tau = tau * scale

    tau_filt = [tau_ind for tau_ind in tau if not (max(tau_ind) > 100)]
    tau = np.asarray(tau_filt)
        
    tot_lines = len(tau[:,0])

    n_vals, b_params, fit_results = voigtfit.get_voigt_fits_and_params(tau, spectra.dvbin, elem=elem, ion=ion, line=line, verbose=False, close=close, EMD=EMD)
    
    if dlogn:
        div_width=dLogN
    else:
        div_width=width
    
    (tot_f_N, NHI_table) = np.histogram(n_vals, NHI_table)
    
    #Absorption distance for each line
    if dX:
        dX=spectra.units.absorption_distance(spectra.box,spectra.red)
        tot_f_N = tot_f_N/(div_width*dX*tot_lines)
    else:
        dz = spectra.units.redshift_distance(spectra.box, spectra.red, spectra.OmegaM)
        tot_f_N = tot_f_N/(div_width*dz*tot_lines)
        
    return np.log10(center), tot_f_N, b_params, np.log10(n_vals), fit_results, tau



def get_flux_power_1D(rs, window=False, tau_thresh=1e6, mean_flux_desired=None, elem="H", ion=1, line=1215):
    #filtering for DLAs sets tau_thresh=1e6 and it will remove power on the low k end
    """Get the power spectrum of (variations in) the flux along the line of sight.
    This is: P_F(k_F) = <d_F d_F>
             d_F = e^-tau / mean(e^-tau) - 1
    Arguments:
        mean_flux_desired: if not None, the spectral optical depths will be rescaled
            to match the desired mean flux.
        window: if True, the flux power spectrum is divided by the window function for the pixel width.
                This interacts poorly with mean flux rescaling.
        tau_thresh: sightlines with a total optical depth greater than this value are removed before mean flux rescaling.
    Output:
        kf, avg_flux_pwoer - the k values and the corresponding calculated power spectrum
    """
    tau = rs.get_tau(elem, ion, line)
    if tau_thresh is not None:
        tau = rs._filter_tau(tau, tau_thresh=tau_thresh)
    (kf, avg_flux_power) = fstat.flux_power(tau, rs.vmax, spec_res=rs.spec_res, window=window, mean_flux_desired=mean_flux_desired)

    return kf, avg_flux_power


def get_flux_power_1D_UVBcorr(rs, window=False, tau_thresh=1e6, UVBcorr=1, elem="H", ion=1, line=1215):
    """Same as get_flux_power_1D but with the ability to rescale the photionizng rate post-processing.
    
    New parameter:
        UVBcorr - value by which to rescale the HI photoionizing rate post-processing
    """
    tau = rs.get_tau(elem, ion, line)
    if tau_thresh is not None:
        tau = rs._filter_tau(tau, tau_thresh=tau_thresh)
    taucorr = tau/UVBcorr
    (kf, avg_flux_power) = fstat.flux_power(taucorr, rs.vmax, spec_res=rs.spec_res, window=window)

    return kf, avg_flux_power

def get_flux_power_1D_taueffcorr(rs, rsmatch, window=False, tau_thresh=1e6, elem="H", ion=1, line=1215):
    """Same as get_flux_power_1D but with the ability to rescale to match the same mean transmitted flux as another file.
    
    New parameter:
        rsmatch - the spectral file you want to match the same mean flux of
    """
    tau = rs.get_tau(elem, ion, line)
    if tau_thresh is not None:
        tau = rs._filter_tau(tau, tau_thresh=tau_thresh)
    mean_flux_desired = rsmatch.get_mean_flux(tau_thresh=tau_thresh)
    (kf, avg_flux_power) = fstat.flux_power(tau, rs.vmax, spec_res=rs.spec_res, window=window, mean_flux_desired=mean_flux_desired)

    return kf, avg_flux_power
